language: c

os:
    - linux

sudo: false

env:
  matrix:
    - PYTHON_VERSION=3.6 SPHINX_VERSION=2.4
    - PYTHON_VERSION=3.6 SPHINX_VERSION=3.2
    - PYTHON_VERSION=3.7 SPHINX_VERSION=2.4
    - PYTHON_VERSION=3.7 SPHINX_VERSION=3.2
    - PYTHON_VERSION=3.8 SPHINX_VERSION=2.4
    - PYTHON_VERSION=3.8 SPHINX_VERSION=3.2

  global:
    - LOCALE=default

install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh
    - pip install -e .[all,docs]

script:
    - make tests
