# AppVeyor.com is a Continuous Integration service to build and run tests under Windows

environment:
  matrix:
    - PY_MAJOR_VER: 3
      PYTHON_ARCH: "x86_64"

build: false

matrix:
    fast_finish: true

platform:
    - x64

os: Visual Studio 2017

install:
    - ps: >-
        if (-Not (Test-Path "C:\Program Files\Pandoc\")) {
          cinst pandoc --no-progress
          cinst graphviz --no-progress
        }
    - ps: $env:Path += ";C:\Program Files\Pandoc\"
    - ps: Start-FileDownload "https://repo.continuum.io/miniconda/Miniconda$env:PY_MAJOR_VER-latest-Windows-$env:PYTHON_ARCH.exe" C:\Miniconda.exe; echo "Finished downloading miniconda"
    - cmd: C:\Miniconda.exe /S /D=C:\Py
    - cmd: SET PATH=C:\Py;C:\Py\Scripts;C:\Py\Library\bin;%PATH%
    - cmd: conda config --set always_yes yes
    - cmd: conda update conda --quiet
    - cmd: conda config --add channels conda-forge
    - cmd: conda config --set channel_priority strict
    - cmd: conda install sphinx werkzeug==0.16.1 alabaster invoke graphviz nbsphinx==0.4.3 --quiet
    - cmd: python -m pip install --upgrade pip
    - cmd: pip install -e .[all]

test_script:
    - python setup.py build_sphinx
    - ps: cd docs
    - ablog build -T
    - ablog build -b latex -T -d .doctrees -w _latex
    - ablog build -T -b json
    - ablog build -T -b pickle
